minimum_pre_commit_version: "2.9.0"
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "v5.0.0"
      hooks:
          - id: debug-statements
    - repo: https://github.com/Zac-HD/shed
      rev: 2024.10.1
      hooks:
          - id: shed
            # args: [--refactor, --py39-plus]
            types_or: [python, markdown, rst]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
