minimum_pre_commit_version: "2.9.0"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: debug-statements
  - repo: https://github.com/Zac-HD/shed
    rev: 2023.5.1
    hooks:
      - id: shed
        # args: [--refactor, --py39-plus]
        types_or: [python, markdown, rst]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
